---
# tasks file for ansible-role-unarchive

- include_vars: "{{ ansible_os_family }}.yml"

- name: Install unarchivers
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ unarchive_packages }}"
